-- This query calculates the total revenue generated by each film, grouped by title and genre.

SELECT 					
	D.title, 				
	F.name AS genre, 				
	COALESCE(SUM(A.amount), 0) AS revenue				
FROM film D					
	INNER JOIN film_category E ON D.film_id = E.film_id
	INNER JOIN category F ON E.category_id = F.category_id		
	LEFT JOIN inventory C ON D.film_id = C.film_id
	LEFT JOIN rental B ON C.inventory_id = B.inventory_id
	LEFT JOIN payment A ON A.rental_id = B.rental_id
GROUP BY 
  	D.title, 
  	F.name					
ORDER BY 
  	revenue DESC, 
  	genre, 
  	title;
